### ISSUE TITLE
cannot enable the "Webots exporter" add-on

### ISSUE THREAD

**Issue by helloliver** [cyberbotics/blender-webots-exporter#10]
When I enable the "Webots exporter" add-on in `Blender / Preferences / Add-ons / Community`,  there is an ERROR!
ImportError: cannot import name 'orientation_helper_factory' from 'bpy_extras.io_utils' (C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy_extras\io_utils.py);
It seems that blender has changed quite a few things since v2.80.

**Comment by DavidMansolino** [comment]
Unfortunately, the exporter was tested only with Blender up to 2.7x.
There are indeed probably some updates to perform to support Blender 2.8x.

**Comment by komjum6** [comment]
Does this get addressed in the near future?

**Comment by DavidMansolino** [comment]
Webots now supports importing directly various 3D file format (https://cyberbotics.com/doc/guide/the-user-interface#file-menu, see Import 3D Model) so the interest of this script is a bit lower now.
