### ISSUE TITLE
Is this still the suggested approach for Webots2022?

### ISSUE THREAD

**Issue by GearsAD** [cyberbotics/blender-webots-exporter#12]
We're trying to import a complex model into Webots and we're looking for the best way to do this (model, UV's, etc.). Is this plugin still the suggested approach or is there a new way to do it? It looks like this is out of date.

**Comment by omichel** [comment]
Unfortunately, this exporter is not maintained any more.
The recommended way to import 3D models, including UV, is to export the Blender model in OBJ or Collada format and use it in Webots with the [CadShape](https://cyberbotics.com/doc/reference/cadshape) node that references the OBJ or Collada file.

**Comment by GearsAD** [comment]
We'll try that, thanks for the quick response!
